##########################################################################
# Name                                                                   #
##########################################################################

name: $(majorVersion).$(minorVersion).$(patch)

##########################################################################
#       Variables                                                        #
##########################################################################
variables:
  majorVersion: 1     
  minorVersion: 0
  patch: $[counter(format('{0}.{1}', variables['MajorVersion'], variables['MinorVersion']), 0)]
  buildNumber: $(MajorVersion).$(MinorVersion).$(Patch)
