##########################################################################
# Name                                                                   #
##########################################################################

name: $(majorVersion).$(minorVersion).$(patch)

##########################################################################
#       Variables                                                        #
##########################################################################
variables:
  majorVersion: 1     
  minorVersion: 0
  patch: $[counter(format('{0}.{1}', variables['MajorVersion'], variables['MinorVersion']), 0)]
  buildNumber: $(MajorVersion).$(MinorVersion).$(Patch)
  rgName: "rg-dbaautomation"          #   The Resource Group name     #  
  rgLocation: "westeurope"            #   The region location         #
  ip: "84.107.159.55"                 #   The public IP address       # 
  azSqlDatabaseName: "Estate"         #   The Azure SQL database name #
  azSQLServerName: "sqlestate"        #   The Azure SQL server name   #
  adminSqlLogin: "SqlAdministrator"   #   The Azure SQL login         #
  artifactName: "DBOPackage"          #   The artifact name           #

##########################################################################
#                                                                        #
#               Deploy Azure SQL in Azure                                #
#                                                                        #
##########################################################################

stages:
  - stage: "CreateDB"
    displayName: "Create database"
    jobs:

      ##########################################################################
      #       Job: Create Azure SQL                                            #
      ##########################################################################

      - job: "Database"
        displayName: "Create database"
        pool: 
          vmImage: 'windows-latest'

        steps:
          - task: AzurePowerShell@5
            name: "Database"
            displayName: "Create Azure SQL database"
            inputs:
              azureSubscription: "ServiceConnection"
              ScriptType: "InlineScript"
              Inline: |
                  # Dot source the script to load the function
                  . ./psscripts/New-AzureSqlDatabase.ps1

                  # Specify the parameters for the script
                  $params = @{
                  resourceGroupName = '$(rgName)'
                  sqlServerName = '$(azSQLServerName)'
                  sqlDatabaseName = '$(azSqlDatabaseName'
                  publicIP = '$(ip)'
                  sqlAdministrator = '$(adminSqlLogin)'
                  sqlPassword = '$(adminSqlPassword)'
                  }
                  New-AzureSqlDatabase @params
                
              azurePowerShellVersion: "LatestVersion"

##########################################################################
#                                                                        #
#               Create package and Publish artifact                      #
#                                                                        #
##########################################################################

  - stage: "Build"
    displayName: "Build package"
    dependsOn: "CreateDB"
      
    jobs:

      ##########################################################################
      #       Job: Create package and artifact                                 #
      ##########################################################################
      
      - job:
        displayName: "Build database package"
        pool: 
          vmImage: 'windows-latest'
          
        steps:
          - task: PowerShell@2
            displayName: "Create database package"
            inputs:
              targetType: "inline"
              script: |
                # Get the connection string
                $connectionString = "$(azSQLServerName)" + ".database.windows.net"

                # Install module 
                Install-Module dbops -Force -Scope CurrentUser

                # Create the package
                $build = Invoke-DBOPackageCI -Path $(System.DefaultWorkingDirectory)\package\$(artifactName).zip -ScriptPath .\opsscripts -Version 1.0

                # Update the build number from DBOPackage
                Write-Host "##vso[build.updatebuildnumber]$($build.Version)"

                # Update the config
                Update-DBOConfig $(System.DefaultWorkingDirectory)\package\$(artifactName).zip -Configuration @{ SqlInstance = "$connectionString"; Database = "$(azSqlDatabaseName)"; }
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)\package\$(artifactName).zip'
              artifact: $(artifactName)
              publishLocation: "pipeline"